# Generated by Django 4.2.1 on 2023-05-18 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_traffic',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='today_record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 8, 1, 36, 439207, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='today_traffic',
            name='person_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
