# Generated by Django 4.2.1 on 2023-05-19 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_today_traffic_people_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Today_Traffic',
            new_name='Foot_Traffic',
        ),
        migrations.AlterField(
            model_name='today_record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 1, 54, 50, 473365)),
        ),
    ]
