# Generated by Django 4.0 on 2023-05-21 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_foot_record_delete_today_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 4, 34, 6, 516472)),
        ),
    ]
