# Generated by Django 4.0 on 2023-05-22 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_population_timerecord_alter_foot_record_count_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Population_TimeRecord',
        ),
        migrations.AlterField(
            model_name='foot_record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 43, 2, 72545)),
        ),
    ]
