# Generated by Django 4.2.1 on 2023-05-28 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0008_delete_population_timerecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.AlterField(
            model_name='foot_record',
            name='count_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 21, 38, 56, 419210)),
        ),
    ]
